## Introdução em Python

In [6]:
import time
contador = 1
while contador < 10:
    print('10')
    contador = contador + 1
    time.sleep(1)
print('Agora deu certo!')

10
10
10
10
10
10
10
10
10
Agora deu certo!


In [22]:
def janela(t):
    import time
    print('Está janela vai abrir em alguns segundos!!!')
    while t >= 0:
        print(t, end='...')
        time.sleep(1)
        t -= 1
    print('\nAcabou o tempo!')

t=3

In [23]:
janela(t)

Está janela vai abrir em alguns segundos!!!
3...2...1...0...
Acabou o tempo!


In [18]:
import time

def regressiva(t):
    while t:
        mins, secs = divmod(t, 60)
        timeformat = '{:02d}:{:02d}'.format(mins, secs)
        print(timeformat, end='\r')
        time.sleep(1)
        t -= 1
    print('Acabou o tempo!')

In [19]:
regressiva(t)

Acabou o tempo!


In [30]:
# importando método sleep que suspende a execução por alguns segundos
from time import sleep
# imprimindo cabeçalho
print('</2020>')
# pausa de 1 segundo
sleep(1)
print('CONTAGEM REGRESSIVA PARA 2021')
# laço que começa em 10 até 0 com passo -1
for cont in range(10, -1, -1):
    # imprimindo o contador
    print(cont)
    # pausa de 1 segundo
    sleep(1)
# imprimindo as mensagens 
print('Feliz ano novo!')
print('<2021>')
print('Fogo!!!!',end='\n')

</2020>
CONTAGEM REGRESSIVA PARA 2021
10
9
8
7
6
5
4
3
2
1
0
Feliz ano novo!
<2021>
Fogo!!!!


In [27]:
numero = int(input('Digite um número! '))
fatorial = numero
cont = 1
while (numero - cont) > 1:
    fatorial = fatorial * (numero - cont)
    cont += 1
print('O fatorial de é {0}! = {1}'.format(numero, fatorial))

Digite um número! 5
O fatorial de é 5! = 120


In [1]:
notas = [0, 0, 0, 0, 0]
soma = 0
x = 0

while x < 5:
    notas[x] = float(input('Nota %d :'%x))
    soma += notas[x]
    x += 1
x = 0
print('\n')
while x < 5:
    print('Nota %d: %6.2f' % (x, notas[x]))
    x += 1

print('\nA soma dos números é ', soma)
print('\nMedia: %5.2f' %(soma/x))

Nota 0 :9
Nota 1 :9
Nota 2 :9
Nota 3 :9
Nota 4 :9


Nota 0:   9.00
Nota 1:   9.00
Nota 2:   9.00
Nota 3:   9.00
Nota 4:   9.00

A soma dos números é  45.0

Media:  9.00


In [56]:
L = []

while True:
    n = int(input('Digite um número, ou 0 para sair. '))
    
    if n == 0:
        break
    L.append(n)
    
x = 0

while x < len(L):
    print('\n', [L])
    x = x + 1

Digite um número, ou 0 para sair. 2
Digite um número, ou 0 para sair. 3
Digite um número, ou 0 para sair. 0

 [[2, 3]]

 [[2, 3]]


In [55]:
import random
state = ['MG', 'SP', 'RJ', 'ES']
escolhido = random.choice(state)
print('O estado escolhido foi {}!'.format(escolhido))

O estado escolhido foi MG!


In [67]:
facil = (1, 25)
escolho = random.choice(facil)
print(escolho)

1


In [68]:
x = [2, 4, 10, 6]
y = []
for i in x:
    y.append(float(i))
print(y)

[2.0, 4.0, 10.0, 6.0]


In [74]:
#chave:valores
dicionario = {
    'Python': 'Data Science', 
    'Programador': 'Tiago',
    'PC': 'Notebook',
    'Nota': 100
}

In [73]:
dicionario['Python']

'Data Science'

In [75]:
dicionario['Pre-requisito'] = 'Python Basico'

In [76]:
print(dicionario)

{'Python': 'Data Science', 'Programador': 'Tiago', 'PC': 'Notebook', 'Nota': 100, 'Pre-requisito': 'Python Basico'}


In [80]:
dicionario.values()

dict_values(['Data Science', 'Tiago', 'Notebook', 100, 'Python Basico'])

In [77]:
dicionario.keys()

dict_keys(['Python', 'Programador', 'PC', 'Nota', 'Pre-requisito'])

In [81]:
dicionario.items()

dict_items([('Python', 'Data Science'), ('Programador', 'Tiago'), ('PC', 'Notebook'), ('Nota', 100), ('Pre-requisito', 'Python Basico')])

In [82]:
# Limpa o dicionario
#dicionario.clear() 

In [2]:
frase = 'Python é tudo de bom!'

In [5]:
frase[2:]

'thon é tudo de bom!'

In [7]:
frase.count('o')

3

In [8]:
len(frase)

21

In [9]:
frase.replace('tudo', '7u|)0')

'Python é 7u|)0 de bom!'

In [19]:
def somaQuadrado(a, b):
    somaQ = a ** 2 + b ** 2
    return somaQ

In [20]:
somaQuadrado(2, 3)

13

In [21]:
print(soma)

45.0


In [22]:
somaQuadrado2 = lambda a, b: a ** 2 + b ** 2

In [23]:
somaQuadrado2(2, 3)

13

In [24]:
x = lambda f: f / 2

In [25]:
x(10)

5.0

In [26]:
kph = [10, 20, 34, 55, 69, 79, 99, 120]

In [27]:
mph = []
for i in kph:
    mph.append(i / 1.61)
print(mph)

[6.211180124223602, 12.422360248447204, 21.11801242236025, 34.161490683229815, 42.857142857142854, 49.06832298136646, 61.49068322981366, 74.53416149068323]


In [29]:
mph2 = list(map(lambda x: x /1.61, kph))
print(mph2)

[6.211180124223602, 12.422360248447204, 21.11801242236025, 34.161490683229815, 42.857142857142854, 49.06832298136646, 61.49068322981366, 74.53416149068323]


In [30]:
mph3 = [x / 1.61 for x in kph]
print(mph3)

[6.211180124223602, 12.422360248447204, 21.11801242236025, 34.161490683229815, 42.857142857142854, 49.06832298136646, 61.49068322981366, 74.53416149068323]


In [31]:
caracteres = [i for i in 'Tiago_Rodrigues_Code']

In [32]:
print(caracteres)

['T', 'i', 'a', 'g', 'o', '_', 'R', 'o', 'd', 'r', 'i', 'g', 'u', 'e', 's', '_', 'C', 'o', 'd', 'e']


In [33]:
len(caracteres)

20

In [37]:
import numpy as np

In [38]:
a = np.array([1, 2, 3])

In [39]:
print(a)

[1 2 3]


In [40]:
b = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)])

In [41]:
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [45]:
c = np.zeros((5, 5))

In [46]:
print(c)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [49]:
d = np.ones((5, 5))

In [50]:
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [51]:
e = np.eye(5)

In [52]:
print(e)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [53]:
b.max()

9

In [54]:
b.min()

1

In [55]:
b.sum()

45

In [56]:
b.mean()

5.0

In [57]:
b.std()

2.581988897471611

In [58]:
import pandas as pd

In [71]:
dados = pd.read_csv('csv/Financial-Sample.csv')

In [69]:
dados.head()

Segment                   Country    Product   Discount Band   \
0  Government  United States of America      Paseo             Low    
1  Government                    France   Amarilla            None    
2  Government                   Germany       Velo             Low    
3  Government                   Germany   Amarilla             Low    
4  Government                   Germany       Velo             Low    

   Units Sold Manufacturing Price Sale Price    Gross Sales   Discounts  \
0      3450.0              $10.00    $350.00  $1,207,500.00  $48,300.00   
1      2750.0             $260.00    $350.00    $962,500.00       $0.00   
2      2966.0             $120.00    $350.00  $1,038,100.00  $20,762.00   
3      2966.0             $260.00    $350.00  $1,038,100.00  $20,762.00   
4      2877.0             $120.00    $350.00  $1,006,950.00  $20,139.00   

           Sales         COGS       Profit       Date  Month Number  \
0  $1,159,200.00  $897,000.00  $262,200.00   7/1/2014             7   
1    $962,500.00  $715,000.00  $247,500.00   2/1/2014             2   
2  $1,017,338.00  $771,160.00  $246,178.00  10/1/2013            10   
3  $1,017,338.00  $771,160.00  $246,178.00  10/1/2013            10   
4    $986,811.00  $748,020.00  $238,791.00  10/1/2014            10   

   Month Name   Year  
0        July   2014  
1    February   2014  
2     October   2013  
3     October   2013  
4     October   2014

In [73]:
dados2 = pd.read_csv('csv/athlete_events.csv')

In [77]:
dados2.head(10)

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   
5   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   
6   5  Christine Jacoba Aaftink   F  25.0   185.0    82.0     Netherlands   
7   5  Christine Jacoba Aaftink   F  25.0   185.0    82.0     Netherlands   
8   5  Christine Jacoba Aaftink   F  27.0   185.0    82.0     Netherlands   
9   5  Christine Jacoba Aaftink   F  27.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season         City          Sport  \
0  CHN  1992 Summer  1992  Summer    Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer       London           Judo   
2  DEN  1920 Summer  1920  Summer    Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer        Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter      Calgary  Speed Skating   
5  NED  1988 Winter  1988  Winter      Calgary  Speed Skating   
6  NED  1992 Winter  1992  Winter  Albertville  Speed Skating   
7  NED  1992 Winter  1992  Winter  Albertville  Speed Skating   
8  NED  1994 Winter  1994  Winter  Lillehammer  Speed Skating   
9  NED  1994 Winter  1994  Winter  Lillehammer  Speed Skating   

                                Event Medal  
0         Basketball Men's Basketball   NaN  
1        Judo Men's Extra-Lightweight   NaN  
2             Football Men's Football   NaN  
3         Tug-Of-War Men's Tug-Of-War  Gold  
4    Speed Skating Women's 500 metres   NaN  
5  Speed Skating Women's 1,000 metres   NaN  
6    Speed Skating Women's 500 metres   NaN  
7  Speed Skating Women's 1,000 metres   NaN  
8    Speed Skating Women's 500 metres   NaN  
9  Speed Skating Women's 1,000 metres   NaN

In [79]:
alunos = {'Nome': ['Tiago', 'Carolina', 'Angel', 'Albert'],
          'Nota': [6, 8, 7, 5],
          'Aprovado': ['Sim', 'Sim', 'Sim', 'Não']}

In [82]:
dataframe = pd.DataFrame(alunos)

In [83]:
dataframe

Nome  Nota Aprovado
0     Tiago     6      Sim
1  Carolina     8      Sim
2     Angel     7      Sim
3    Albert     5      Não

In [84]:
objeto1 = pd.Series([2, 6, 10, 15])
print(objeto1)

0     2
1     6
2    10
3    15
dtype: int64


In [85]:
array1 = np.array([6, 12, 2, 9, 10])
array2 = np.array([(2, 6, 10, 15), (6, 12, 14, 13)])
print(array1)
print(array2)

[ 6 12  2  9 10]
[[ 2  6 10 15]
 [ 6 12 14 13]]


In [86]:
objeto2 = pd.Series(array1)
print(objeto2)

0     6
1    12
2     2
3     9
4    10
dtype: int64


In [87]:
alunosDIC = {'Nome': ['Carla', 'Carolina', 'Angela', 'Alberto'],
          'Nota': [6, 8, 3, 5],
          'Aprovado': ['Sim', 'Sim', 'Não', 'Não']}

In [88]:
alunosDF = pd.DataFrame(alunosDIC)

In [89]:
print(alunosDF)

       Nome  Nota Aprovado
0     Carla     6      Sim
1  Carolina     8      Sim
2    Angela     3      Não
3   Alberto     5      Não


In [90]:
alunosDF.head()

Nome  Nota Aprovado
0     Carla     6      Sim
1  Carolina     8      Sim
2    Angela     3      Não
3   Alberto     5      Não

In [92]:
alunosDF.shape

(4, 3)

In [93]:
alunosDF.min()

Nome        Alberto
Nota              3
Aprovado        Não
dtype: object

In [94]:
alunosDF.max()

Nome        Carolina
Nota               8
Aprovado         Sim
dtype: object

In [95]:
alunosDF.describe()

Nota
count  4.000000
mean   5.500000
std    2.081666
min    3.000000
25%    4.500000
50%    5.500000
75%    6.500000
max    8.000000

In [96]:
alunosDF['Nome']

0       Carla
1    Carolina
2      Angela
3     Alberto
Name: Nome, dtype: object

In [97]:
alunosDF['Nota']

0    6
1    8
2    3
3    5
Name: Nota, dtype: int64

In [98]:
alunosDF['Aprovado']

0    Sim
1    Sim
2    Não
3    Não
Name: Aprovado, dtype: object

In [99]:
alunosDF.loc[[0]]

Nome  Nota Aprovado
0  Carla     6      Sim

In [100]:
alunosDF.loc[[1]]

Nome  Nota Aprovado
1  Carolina     8      Sim

In [101]:
alunosDF.loc[[2]]

Nome  Nota Aprovado
2  Angela     3      Não

In [102]:
alunosDF.loc[[3]]

Nome  Nota Aprovado
3  Alberto     5      Não

In [103]:
alunosDF.loc[[0, 3]]

Nome  Nota Aprovado
0    Carla     6      Sim
3  Alberto     5      Não

In [104]:
alunosDF.loc[[1, 2]]

Nome  Nota Aprovado
1  Carolina     8      Sim
2    Angela     3      Não

In [106]:
alunosDF.loc[1:3]

Nome  Nota Aprovado
1  Carolina     8      Sim
2    Angela     3      Não
3   Alberto     5      Não

In [107]:
alunosDF.loc[alunosDF['Nome'] == 'Carolina']

Nome  Nota Aprovado
1  Carolina     8      Sim

In [108]:
alunosDF.loc[alunosDF['Nome'] == 'Tiago']

Empty DataFrame
Columns: [Nome, Nota, Aprovado]
Index: []

In [109]:
alunosDF.loc[alunosDF['Nota'] == 8]

Nome  Nota Aprovado
1  Carolina     8      Sim

In [110]:
alunosDF.loc[alunosDF['Aprovado'] == 'Não']

Nome  Nota Aprovado
2   Angela     3      Não
3  Alberto     5      Não

In [111]:
alunosDF.loc[alunosDF['Aprovado'] == 'Sim']

Nome  Nota Aprovado
0     Carla     6      Sim
1  Carolina     8      Sim

In [112]:
aprovadoSim = alunosDF.loc[alunosDF['Aprovado'] == 'Sim']

In [113]:
print(aprovadoSim)

       Nome  Nota Aprovado
0     Carla     6      Sim
1  Carolina     8      Sim


In [118]:
aprovadoNao = alunosDF.loc[alunosDF['Nota'] <= 5]

In [119]:
print(aprovadoNao)

      Nome  Nota Aprovado
2   Angela     3      Não
3  Alberto     5      Não


In [120]:
aprovadoNao1 = alunosDF.loc[alunosDF['Aprovado'] != 'Sim']

In [121]:
print(aprovadoNao1)

      Nome  Nota Aprovado
2   Angela     3      Não
3  Alberto     5      Não


In [122]:
dados2.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [123]:
dados2.rename(columns = {'Name': 'Nome', 'Sex': 'Sexo', 'Age': 'idade', 'Height': 'Altura', 'Weight': 'Peso'})

ID                      Nome Sexo  idade  Altura  Peso  \
0            1                 A Dijiang    M   24.0   180.0  80.0   
1            2                  A Lamusi    M   23.0   170.0  60.0   
2            3       Gunnar Nielsen Aaby    M   24.0     NaN   NaN   
3            4      Edgar Lindenau Aabye    M   34.0     NaN   NaN   
4            5  Christine Jacoba Aaftink    F   21.0   185.0  82.0   
...        ...                       ...  ...    ...     ...   ...   
271111  135569                Andrzej ya    M   29.0   179.0  89.0   
271112  135570                  Piotr ya    M   27.0   176.0  59.0   
271113  135570                  Piotr ya    M   27.0   176.0  59.0   
271114  135571        Tomasz Ireneusz ya    M   30.0   185.0  96.0   
271115  135571        Tomasz Ireneusz ya    M   34.0   185.0  96.0   

                  Team  NOC        Games  Year  Season            City  \
0                China  CHN  1992 Summer  1992  Summer       Barcelona   
1                China  CHN  2012 Summer  2012  Summer          London   
2              Denmark  DEN  1920 Summer  1920  Summer       Antwerpen   
3       Denmark/Sweden  DEN  1900 Summer  1900  Summer           Paris   
4          Netherlands  NED  1988 Winter  1988  Winter         Calgary   
...                ...  ...          ...   ...     ...             ...   
271111        Poland-1  POL  1976 Winter  1976  Winter       Innsbruck   
271112          Poland  POL  2014 Winter  2014  Winter           Sochi   
271113          Poland  POL  2014 Winter  2014  Winter           Sochi   
271114          Poland  POL  1998 Winter  1998  Winter          Nagano   
271115          Poland  POL  2002 Winter  2002  Winter  Salt Lake City   

                Sport                                     Event Medal  
0          Basketball               Basketball Men's Basketball   NaN  
1                Judo              Judo Men's Extra-Lightweight   NaN  
2            Football                   Football Men's Football   NaN  
3          Tug-Of-War               Tug-Of-War Men's Tug-Of-War  Gold  
4       Speed Skating          Speed Skating Women's 500 metres   NaN  
...               ...                                       ...   ...  
271111           Luge                Luge Mixed (Men)'s Doubles   NaN  
271112    Ski Jumping  Ski Jumping Men's Large Hill, Individual   NaN  
271113    Ski Jumping        Ski Jumping Men's Large Hill, Team   NaN  
271114      Bobsleigh                      Bobsleigh Men's Four   NaN  
271115      Bobsleigh                      Bobsleigh Men's Four   NaN  

[271116 rows x 15 columns]

In [124]:
dados2.head()

ID                      Name Sex   Age  Height  Weight            Team  \
0   1                 A Dijiang   M  24.0   180.0    80.0           China   
1   2                  A Lamusi   M  23.0   170.0    60.0           China   
2   3       Gunnar Nielsen Aaby   M  24.0     NaN     NaN         Denmark   
3   4      Edgar Lindenau Aabye   M  34.0     NaN     NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink   F  21.0   185.0    82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [125]:
dados2.rename(columns={'Name': 'Nome', 'Sex': 'Sexo', 'Age': 'idade', 'Height': 'Altura', 'Weight': 'Peso'}, inplace=True)

In [126]:
dados2.head()

ID                      Nome Sexo  idade  Altura  Peso            Team  \
0   1                 A Dijiang    M   24.0   180.0  80.0           China   
1   2                  A Lamusi    M   23.0   170.0  60.0           China   
2   3       Gunnar Nielsen Aaby    M   24.0     NaN   NaN         Denmark   
3   4      Edgar Lindenau Aabye    M   34.0     NaN   NaN  Denmark/Sweden   
4   5  Christine Jacoba Aaftink    F   21.0   185.0  82.0     Netherlands   

   NOC        Games  Year  Season       City          Sport  \
0  CHN  1992 Summer  1992  Summer  Barcelona     Basketball   
1  CHN  2012 Summer  2012  Summer     London           Judo   
2  DEN  1920 Summer  1920  Summer  Antwerpen       Football   
3  DEN  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  NED  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [127]:
dados2['Medal'].value_counts()

Gold      13372
Bronze    13295
Silver    13116
Name: Medal, dtype: int64

In [128]:
dados2['City'].value_counts()

London                    22426
Athina                    15556
Sydney                    13821
Atlanta                   13780
Rio de Janeiro            13688
Beijing                   13602
Barcelona                 12977
Los Angeles               12423
Seoul                     12037
Munich                    10304
Montreal                   8641
Mexico City                8588
Helsinki                   8270
Roma                       8119
Tokyo                      7702
Moskva                     7191
Paris                      7169
Berlin                     6506
Amsterdam                  4992
Sochi                      4891
Melbourne                  4829
Vancouver                  4402
Torino                     4382
Stockholm                  4338
Antwerpen                  4292
Salt Lake City             4109
Innsbruck                  3639
Nagano                     3605
Albertville                3436
Lillehammer                3160
Calgary                    2639
Sarajevo

In [129]:
dados2['Games'].value_counts()

2000 Summer    13821
1996 Summer    13780
2016 Summer    13688
2008 Summer    13602
2004 Summer    13443
1992 Summer    12977
2012 Summer    12920
1988 Summer    12037
1972 Summer    10304
1984 Summer     9454
1976 Summer     8641
1968 Summer     8588
1952 Summer     8270
1960 Summer     8119
1964 Summer     7702
1980 Summer     7191
1936 Summer     6506
1948 Summer     6405
1924 Summer     5233
1956 Summer     5127
1928 Summer     4992
2014 Winter     4891
2010 Winter     4402
2006 Winter     4382
1920 Summer     4292
2002 Winter     4109
1912 Summer     4040
1998 Winter     3605
1992 Winter     3436
1994 Winter     3160
1908 Summer     3101
1932 Summer     2969
1988 Winter     2639
1984 Winter     2134
1900 Summer     1936
1968 Winter     1891
1976 Winter     1861
1964 Winter     1778
1980 Winter     1746
1906 Summer     1733
1972 Winter     1655
1956 Winter     1307
1904 Summer     1301
1960 Winter     1116
1952 Winter     1088
1948 Winter     1075
1936 Winter      895
1928 Winter  

In [130]:
dados2['Sexo'].value_counts()

M    196594
F     74522
Name: Sexo, dtype: int64

In [131]:
dados2.describe()

ID          idade         Altura           Peso  \
count  271116.000000  261642.000000  210945.000000  208241.000000   
mean    68248.954396      25.556898     175.338970      70.702393   
std     39022.286345       6.393561      10.518462      14.348020   
min         1.000000      10.000000     127.000000      25.000000   
25%     34643.000000      21.000000     168.000000      60.000000   
50%     68205.000000      24.000000     175.000000      70.000000   
75%    102097.250000      28.000000     183.000000      79.000000   
max    135571.000000      97.000000     226.000000     214.000000   

                Year  
count  271116.000000  
mean     1978.378480  
std        29.877632  
min      1896.000000  
25%      1960.000000  
50%      1988.000000  
75%      2002.000000  
max      2016.000000

In [132]:
dados2.drop('ID', axis = 1, inplace = True)

In [133]:
dados2.head()

Nome Sexo  idade  Altura  Peso            Team  NOC  \
0                 A Dijiang    M   24.0   180.0  80.0           China  CHN   
1                  A Lamusi    M   23.0   170.0  60.0           China  CHN   
2       Gunnar Nielsen Aaby    M   24.0     NaN   NaN         Denmark  DEN   
3      Edgar Lindenau Aabye    M   34.0     NaN   NaN  Denmark/Sweden  DEN   
4  Christine Jacoba Aaftink    F   21.0   185.0  82.0     Netherlands  NED   

         Games  Year  Season       City          Sport  \
0  1992 Summer  1992  Summer  Barcelona     Basketball   
1  2012 Summer  2012  Summer     London           Judo   
2  1920 Summer  1920  Summer  Antwerpen       Football   
3  1900 Summer  1900  Summer      Paris     Tug-Of-War   
4  1988 Winter  1988  Winter    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [134]:
dados2.drop('NOC', axis = 1, inplace = True)
dados2.drop('Season', axis = 1, inplace = True)

In [135]:
dados2.head()

Nome Sexo  idade  Altura  Peso            Team  \
0                 A Dijiang    M   24.0   180.0  80.0           China   
1                  A Lamusi    M   23.0   170.0  60.0           China   
2       Gunnar Nielsen Aaby    M   24.0     NaN   NaN         Denmark   
3      Edgar Lindenau Aabye    M   34.0     NaN   NaN  Denmark/Sweden   
4  Christine Jacoba Aaftink    F   21.0   185.0  82.0     Netherlands   

         Games  Year       City          Sport  \
0  1992 Summer  1992  Barcelona     Basketball   
1  2012 Summer  2012     London           Judo   
2  1920 Summer  1920  Antwerpen       Football   
3  1900 Summer  1900      Paris     Tug-Of-War   
4  1988 Winter  1988    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [136]:
dados2.rename(columns={'Team': 'Time', 'Games': 'Jogos', 'Year': 'Ano', 'City': 'Cidade'}, inplace=True)

In [137]:
dados2.head()

Nome Sexo  idade  Altura  Peso            Time  \
0                 A Dijiang    M   24.0   180.0  80.0           China   
1                  A Lamusi    M   23.0   170.0  60.0           China   
2       Gunnar Nielsen Aaby    M   24.0     NaN   NaN         Denmark   
3      Edgar Lindenau Aabye    M   34.0     NaN   NaN  Denmark/Sweden   
4  Christine Jacoba Aaftink    F   21.0   185.0  82.0     Netherlands   

         Jogos   Ano     Cidade          Sport  \
0  1992 Summer  1992  Barcelona     Basketball   
1  2012 Summer  2012     London           Judo   
2  1920 Summer  1920  Antwerpen       Football   
3  1900 Summer  1900      Paris     Tug-Of-War   
4  1988 Winter  1988    Calgary  Speed Skating   

                              Event Medal  
0       Basketball Men's Basketball   NaN  
1      Judo Men's Extra-Lightweight   NaN  
2           Football Men's Football   NaN  
3       Tug-Of-War Men's Tug-Of-War  Gold  
4  Speed Skating Women's 500 metres   NaN

In [138]:
dados2.rename(columns={'Event': 'Evento', 'Medal': 'Medalha'}, inplace=True)

In [139]:
dados2.head()

Nome Sexo  idade  Altura  Peso            Time  \
0                 A Dijiang    M   24.0   180.0  80.0           China   
1                  A Lamusi    M   23.0   170.0  60.0           China   
2       Gunnar Nielsen Aaby    M   24.0     NaN   NaN         Denmark   
3      Edgar Lindenau Aabye    M   34.0     NaN   NaN  Denmark/Sweden   
4  Christine Jacoba Aaftink    F   21.0   185.0  82.0     Netherlands   

         Jogos   Ano     Cidade          Sport  \
0  1992 Summer  1992  Barcelona     Basketball   
1  2012 Summer  2012     London           Judo   
2  1920 Summer  1920  Antwerpen       Football   
3  1900 Summer  1900      Paris     Tug-Of-War   
4  1988 Winter  1988    Calgary  Speed Skating   

                             Evento Medalha  
0       Basketball Men's Basketball     NaN  
1      Judo Men's Extra-Lightweight     NaN  
2           Football Men's Football     NaN  
3       Tug-Of-War Men's Tug-Of-War    Gold  
4  Speed Skating Women's 500 metres     NaN

## Histogramas